#!/bin/bash
#SBATCH --job-name=asgn2_job
#SBATCH --time=00:10:00
#SBATCH --mem=20G
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=2
#SBATCH --output=asgn2out.%j.out
#SBATCH --partition=defq

module load openmpi/4.1.5-gcc-11.2.0-ux65npg
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

if [ ! -f asgn2 ]
then
 mpicc asgn2_caas.c -o asgn2
else
 if [ asgn2_caas.c -nt asgn2 ]
 then
  mpicc asgn2_caas.c -o asgn2
  fi
fi

srun asgn2

exit 0
